name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Install deps and build protoscript
      run: |-
        sudo apt install -y protobuf-compiler python3-protobuf
        protoc --python_out=. parser/exposure.proto

    - name: Fetch latest data
      run: |-
        ./scrape.sh

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add erouska
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
